version: "3"

services:
  db:
    image: mysql:8

    ports:
      - 3306:3306

    restart: always

    volumes:
      - ./.docker/volumes/mysql/var/lib/mysql:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: S3cr3t
      MYSQL_USER: turbo
      MYSQL_PASSWORD: S3cr3t
